FROM debian:buster-slim


RUN apt-get update && apt-get upgrade -y 
RUN apt-get -f install
RUN apt-get autoclean
RUN apt-get autoremove




WORKDIR /home/pi/test
COPY bin/click.sh .
RUN chmod +x click.sh



ENTRYPOINT [ "/home/pi/test/click.sh" ]